const actionTypes = {
	//PATIENT
	FETCH_PATIENT_START: "FETCH_PATIENT_START",
	FETCH_PATIENT_SUCCESS: "FETCH_PATIENT_SUCCESS",
	FETCH_PATIENT_FAIL: "FETCH_PATIENT_FAIL",
	ADD_PATIENT: "ADD_PATIENT",
	DELETE_PATIENT: "DELETE_PATIENT",
	EDIT_PATIENT: "EDIT_PATIENT",

	//APPOINTMENT
	FETCH_APPOINTMENT_START: "FETCH_APPOINTMENT_START",
	FETCH_APPOINTMENT_SUCCESS: "FETCH_APPOINTMENT_SUCCESS",
	FETCH_APPOINTMENT_FAIL: "FETCH_APPOINTMENT_FAIL",
	ADD_APPOINTMENT: "ADD_APPOINTMENT",
	DELETE_APPOINTMENT: "DELETE_APPOINTMENT",
	EDIT_APPOINTMENT: "EDIT_APPOINTMENT",

	//PROCESS
	FETCH_PROCESS_START: "FETCH_PROCESS_START",
	FETCH_PROCESS_SUCCESS: "FETCH_PROCESS_SUCCESS",
	FETCH_PROCESS_FAIL: "FETCH_PROCESS_FAIL",
	ADD_PROCESS: "ADD_PROCESS",
	DELETE_PROCESS: "DELETE_PROCESS",
	EDIT_PROCESS: "EDIT_PROCESS",
};

export default actionTypes;
